[project]
name = "penalty-moderator"
authors = ["Anonymous Developer"]
description = "A comprehensive smart contract for managing and incentivizing accountability through financial penalties"
telemetry = false
requirements = []
[contracts.penalty-core]
path = "contracts/penalty-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
